name: 'Metis Test Collector'
description: 'Create metis-otel-collector for github workflow'
inputs:
  connection-string:
    description: Connection string to the instrumented database
    required: true
  metis-api-key:
    description: Metis application api key
    required: true
  github-token:
    description: Github token to publish comments on PR
    required: true
  target-url:
    description: Metis app target url
    default: https://app.metisdata.io
  exporter-target-url:
    description: Metis exporter target url
    default: https://ingest.metisdata.io
  job-network:
    description: Docker job network
    default: ${{ job.container.network }}
  metis-log-level:
    description: Metis collector log level
    default: log
  dump-logs:
    description: Collector dump logs to console
    default: 'false'
  shell:
    description: Shell to execute commands. Defaults to "/bin/sh"
    default: /bin/sh

runs:
  using: node16
  main: dist/index.js
  post: dist/post/index.js
